# GitHub Pages Configuration for Navy Medicine HRIS Tutorials

# Site Settings
title: Navy Medicine HRIS Training Portal
description: Comprehensive training materials for Navy Medicine HR Information Systems
theme: minima

# Navigation
header_pages:
  - index.md
  - Navy_Medicine_HR_Training_Tracks.md
  - DCPDS_Fundamentals_Tutorial.md

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..3

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

# Relative Links
relative_links:
  enabled: true
  collections: true

# Exclude from build
exclude:
  - README.md
  - create_branch_structure.sh
  - organize_with_tags.sh
  - push_to_github.sh
  - .git/
  - .gitignore

# Custom variables
github:
  private: true
  
# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default
      nav_order: 999